### ISSUE TITLE
Infrared port Information

### ISSUE THREAD

**Issue by vamsi765** [UDOOboard/X86-Docs#4]
Hi,

Where can I find information regarding the IR sensor?

Thanks
Vamsi

**Comment by waltervl** [comment]
See commit https://github.com/UDOOboard/X86-Docs/commit/830ccc40d0df8b91d01f8354ef851f5d23be8ba4
or on the website https://www.udoo.org/docs-x86/Hardware_&_Accessories/Consumer_IR.html

**Comment by tuxun** [comment]
damn we waited this info 1 year and it was closed in 6 hour :) ps: thx for link walter
