### ISSUE TITLE
X86-Docs/docs/04_Software_&_OS_Distro/05_LibreELEC_with_CEC_support

### ISSUE THREAD

**Issue by Lino77** [UDOOboard/X86-Docs#5]
X86-Docs/docs/04_Software_&_OS_Distro/05_LibreELEC_with_CEC_support
CEC is not working 
and where is the source

**Comment by ektor5** [comment]
Hi @Lino77,
Sorry, can you provide some more info? Have you upgraded the BIOS to the latest version?
Anyway, the sources of the distro are here: https://github.com/ektor5/LibreELEC.tv
I'll add them to the documentation.

Thanks,
Ettore
